sudo: false

addons:
  sonarcloud:
    organization: "freeeyes-github"
    token: ${SONAR_TOKEN}
    #token:
    #  secure: "WE5cHhZmSfh42Tn9YTi8fNfeyDFsdIcBgwY6GP4q9lE9y7QtMR1AKubKPZECWHcPSFpXfMKwx0uGTTwZGHvAE8o4zNH+1Qjs5twe7NBYSNie0Y+rFhe1Ru+tsOhjEf3RrXN7NILmmAh9fCdwKn6uTY8sJuH+rN2JJDypAH2pxzHm3wJlpX1xco145+u20E4M38Wwct+9SkzpJopMKAYiNkowSKKiADfH467swLzhVpeoKWb/+kz5FNbX1XGoO3k8eQO3AC1vf4l5uyYKhHUSHnQYdlJhROwD8VbL8JiuNfNM+0MyExCtyS3qeep5QsCV5Uf0iw2TFJ+JIKXtxirKAwMXSx+aGpd7AEIPOZHj40LPQAvVRtZ6d52HtlcTyEfyDdfj0exWIneCti7DOzXaBAwBphH6Qdcm87g+ForQ+/JEeujGhs7YIP1VIC78yo0Z4DLonmY5uxQ7KrmaR+RD3NyDbaoSMo0BCF8/V+0TQZJMBuNHxQXa6fTkkEmoefxb+RYI92yAiJAQ373MFpCjrRQ95SK0/UvLNdkUQL3L6066thEdnpEITaUp4bxbEfFnBpHGjAN95AhLkCJz8ubP2zru9/aqEscdMv+75Xp4XK3TuqlQnz9wY11mPMQ4Xx1/DiAFzcl22wB8/BVZs4XMQi1mzSP9hfTD+qmCeh1QKG0="

script:
  # Prepare the build system
  - mkdir build
  - cd build
  - cmake ..
  - cd ..
  - NUMBER_OF_PROCESSORS=$(nproc --all)
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.cache.enabled=true -Dsonar.cfamily.cache.path=${TRAVIS_HOME}/.cfamily -Dsonar.cfamily.threads=${NUMBER_OF_PROCESSORS}
  #- sonar-scanner -X

cache:
  directories:
    - $HOME/.sonar/cache
    # This contains the CFamily cache. According to https://docs.travis-ci.com/user/caching/#pull-request-builds-and-caches,
    # for a PR, it will use the cache of the target branch if the branch of the PR does not already have its cache.
    - $HOME/.cfamily