name: Github-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: commit file
        working-directory: ${{github.workspace}}
        shell: bash         
        run: |
          echo "Test push commit to the remote in the workflow" >> test.txt
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add -f test.txt
          git commit -m "Update test.txt"
          git push
     - name: Commit & Push changes
       uses: actions/push@master
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}

