name: Github-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: commit file
        working-directory: ${{github.workspace}}/include
        shell: bash         
        run: |
          date > test.txt
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add -f test.txt
          git commit -m "[date]Update test.txt"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: ${{ github.ref }}

