name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: g++ -std=c++11 -Wunused-function -o test test_task.cpp -pthread -ldl
    - name: execute
      run: ./test
